name: CI/CD Pipeline for Resource Scheduler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest tests/

    - name: Login to Docker Hub
      run: echo "${{ secrets.Forgetit@now }}" | docker login -u "${{ secrets.elogonyi }}" --password-stdin


    - name: Build Docker Image
      run: docker build -t elogonyi/resource-scheduler .

    - name: Push Docker Image to Docker Hub
      run: docker push elogonyi/resource-scheduler

    - name: Deploy to Cloud
      run: echo "Deployment step here (e.g., AWS, DigitalOcean, etc.)"
